
#define ENABLE_ANGLETOOL
#define ENABLE_ANONYMIZETOOL
#define ENABLE_CORNERANNOTATIONTOOL
#define ENABLE_DICOMEXPORTTOOL
#define ENABLE_DICOMIZETOOL
#define ENABLE_DETACHWINDOWTOOL
#define ENABLE_PIXELSBLURING
#define ENABLE_MARKERTOOL
#define ENABLE_METRICGRIDTOOL
#define ENABLE_NOTETOOL
#define ENABLE_OPENFILETOOL
#define ENABLE_OPENFOLDERTOOL
#define ENABLE_OPENREMOVABLETOOL
#define ENABLE_PANTOOL
#define ENABLE_POINTERTOOL
#define ENABLE_QUERYRETRIEVETOOL
#define ENABLE_RESETTOOL
#define ENABLE_RULETOOL
#define ENABLE_SENDPACSTOOL
#define ENABLE_SHOWTAGSHISTORYTOOL
#define ENABLE_SHOWTAGSTOOL
#define ENABLE_SLIDERTOOL
#define ENABLE_UNDOTOOL
#define ENABLE_WINDOWLAYOUTTOOL
#define ENABLE_WINDOWLEVELTOOL
#define ENABLE_ZOOMTOOL
#define ENABLE_RESETONEONETOOL
#define ENABLE_BRIGHTNESSCONTRASTTOOL


