.\" ========================================================
.\" license: GPL v2 or later
.\" ========================================================

.TH Ginkgo\ CADx 1 "2011 June 22nd" "Manual for Ginkgo CADx"

.SH NAME
ginkgocadx \- a medical image (DICOM) viewer

.SH SYNOPSIS
.B ginkgocadx
[
.RB --version
|
.RB -version
|
.RB -v
]
[
.I <DICOM file>
|
.I <XML integration file>
]


.SH DESCRIPTION
.B Ginkgo CADx
is a solution for working with medical images in the DICOM
format.

.SH OPTIONS
.PP
.TP
.B \--version, \--version, -v
Show version information about Ginkgo CADx.
.TP
.B <DICOM file>
A DICOM file to load on startup.
.TP
.B <XML integration file>
An XML integration file to load on startup.


.SH SEE ALSO
.PP
.TP
.B http://ginkgo-cadx.com
Homepage
.TP
.B /usr/share/doc/ginkgocadx/
Local documentation
